### ISSUE TITLE
Rewrite of type 302 is not working after iPad system update

### ISSUE THREAD

**Issue by NotoOotori** [crossutility/Quantumult-X#105]
- Model: iPad Pro (12.9-inch) (5th generation)
- Software Version: 15.4.1
- Quantumult X Version: 1.0.28
---

I have a rewrite of type 302 to match `^http://(www.)?google.cn` and to redirect to `https://www.google.com`. It was working but it doesn't work anymore since I installed the latest iPadOS 15.4.1 software update. I've tried to change `http` in the regex to `https`, but it still doesn't work. Some screenshots are provided below. Any help is appreciated, and please tell me if any further information is needed.

---
1. Safari Screenshot
![EF2BEFD0-A137-4866-B398-4CC844AAA8B3](https://user-images.githubusercontent.com/39304463/163454785-17a03d30-80bc-43ec-8764-41a4d9b5b14a.jpeg)
2. Activity
![2DE30BCA-B2DC-4D1F-BB79-2C2D28EA64F7](https://user-images.githubusercontent.com/39304463/163454800-c21bab20-8372-4932-892a-305ce8fa12ad.jpeg)
![D97061AA-120E-49DF-B1C7-C742B043F3C5](https://user-images.githubusercontent.com/39304463/163454816-523140f7-19a8-4bec-9c4c-65812e744ea7.jpeg)
3. Rewrite item
![2996A27C-7A71-4A4A-A32E-9EDA010C1573](https://user-images.githubusercontent.com/39304463/163454807-a85ac619-039b-4736-a8ec-e0ecd11e750b.jpeg)
4. Rewrite is enabled
![213AF0E7-DE60-43B6-BDA8-F96A8D74F0DA](https://user-images.githubusercontent.com/39304463/163454815-a23b55e5-a46a-45ce-a596-af60f08a3137.jpeg)

**Comment by KOP-XIAO** [comment]
添加hostname *google.com。更新系统后强制https

**Comment by NotoOotori** [comment]
> 添加hostname *google.com。更新系统后强制https

非常感谢！在 `[mitm]` 中添加了 `hostname = *.google.cn` 之后问题解决了！
