### ISSUE TITLE
建议：增加ipv6白名单功能

### ISSUE THREAD

**Issue by EliceAM** [crossutility/Quantumult-X#115]
个人由于是移动家宽没有公网ipv4,于是使用ipv6+ddns+socks5的方案回家

而配置文件中的no-ipv6一旦开启则直接禁止了所有AAAA解析，后续无法正常回家
但注释掉no-ipv6又会导致部分域名被ipv6抢答导致连接速度缓慢

目前现在有以下几种初步想法，不知可否实现
1.将自定义server=/域名/dns 的列表优先度提升到no-ipv6前面
2.对自定义的dns服务器增加only ipv4解析的选项，而不是全局no-ipv6
3.新增一个no-ipv6的白名单域名列表

期待反馈，感谢大佬

**Comment by jasony9982** [comment]
这个问题现在解决了吗？

**Comment by jasony9982** [comment]
> 个人由于是移动家宽没有公网ipv4,于是使用ipv6+ddns+socks5的方案回家
> 
> 而配置文件中的no-ipv6一旦开启则直接禁止了所有AAAA解析，后续无法正常回家 但注释掉no-ipv6又会导致部分域名被ipv6抢答导致连接速度缓慢
> 
> 目前现在有以下几种初步想法，不知可否实现 1.将自定义server=/域名/dns 的列表优先度提升到no-ipv6前面 2.对自定义的dns服务器增加only ipv4解析的选项，而不是全局no-ipv6 3.新增一个no-ipv6的白名单域名列表
> 
> 期待反馈，感谢大佬

这个问题现在解决了吗？
