### ISSUE TITLE
开启 QuanX 无法建立 IPv6 SSH 连接

### ISSUE THREAD

**Issue by SkysCrystal** [crossutility/Quantumult-X#129]
QuanX 注释了 IPv6 `;no-ipv6`， 在 `filter-local` 中添加了 `ip6-cidr, 主机地址, direct` ，手机出现如下情况：
1. 开启 QuanX 时可以访问 IPv6 网站，访问该 IPv6-only 主机建立的网站，可以正常访问。
2. 当开启 QuanX 时打开 SSH 工具，无法建立与主机 SSH 连接 Connection Closed (no route to host / host is unreachable)。
3. 当关闭 QuanX 时建立起 SSH 连接，再打开 QuanX 时可以继续使用 SSH 访问。

希望能在开启 QuanX 时就能访问 SSH ，求助如何设置，谢谢！

**Comment by thirtykmpersecond** [comment]
我也遇到这个问题

**Comment by gwhcn** [comment]
有解决办法吗，我现在用scrcpy remote远程连接ipv6设备也是报failed to connect to <ipv6地址:端口>: No route to host，需要关闭quanX才能连接，很麻烦

**Comment by gwhcn** [comment]
换用Stash了，开启Tunnel IPv6路由后可以使用IPv6 SSH连接

**Comment by gwhcn** [comment]
找到解决办法了，其他设置-兼容性增强，开启

**Comment by SkysCrystal** [comment]
> 找到解决办法了，其他设置-兼容性增强，开启

太感谢了！问题解决啦！

**Comment by thirtykmpersecond** [comment]
> 找到解决办法了，其他设置-兼容性增强，开启

这个方法是走IPv6直连，并不会根据规则走proxy，你可以测试一下

**Comment by iamvicliu** [comment]
兼容模式解决问题，感谢楼上
