### ISSUE TITLE
[Bug]ipv6节点无法连接

### ISSUE THREAD

**Issue by MegaSuite** [crossutility/Quantumult-X#191]
前置条件：
- 配置文件内的`"no-system""no-ipv6"`都已注释，没有打开。
- 已经启用了兼容性模式。
- 也添加了分流规则`ip6-cidr,::/0,DIRECT`。

如果我手动添加一个节点，假设如下：

    trojan=[2406:9b80:3333:abce::1]:23333, password=xxxxxx, over-tls=true, tls-verification=false, fast-open=false, udp-relay=true, tag=hk1

这样是可以连接的。

但如果我使用解析到此ipv6的AAAA类型域名记录便不能连接，假设如下：

    trojan=hk.ddddfffffd.com:23333, password=xxxxxx, over-tls=true, tls-verification=false, fast-open=false, udp-relay=true, tag=hk1

区别如下：
```text
trojan=[2406:9b80:3333:abce::1]:23333
trojan=hk.ddddfffffd.com:23333
```

是否是因为节点内的AAAA类型无法解析，请求解决或修复。

**Comment by MegaSuite** [comment]
问题已解决，通过在配置文件中添加ipv6 dns解决

**Comment by ljtao020** [comment]
> 问题已解决，通过在配置文件中添加ipv6 dns解决

大佬能教一下具体操作吗

**Comment by MegaSuite** [comment]
> > 问题已解决，通过在配置文件中添加ipv6 dns解决
> 
> 大佬能教一下具体操作吗

在配置文件`xxx.conf`里添加ipv6 dns
比如`server=[2400:3200:baba::1]`，就可以连接了。

但目前还是有一些问题，比如无法通过ipv6连接ssh（个人认为是软件本身问题，其他的代理软件没有见过这种问题）。
