### ISSUE TITLE
qx在使用腾讯视频时严重发热（接近于玩一些一小段游戏的发热了），关闭qx，或者使用完全相同配置loon时发热正常

### ISSUE THREAD

**Issue by Skyxim** [crossutility/Quantumult-X#74]
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/Advertising/Advertising.conf
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Rewrite/Block/Advertising.conf
排查发现可能是腾讯相关的mitm或者重写引起的，以上两条订阅都会导致发热，但是问题在于loon我也是使用完全同一个重写，并且对比了腾讯相关重写和mitm完全相同，但是并没有严重发热现象

手机Iphone12 mini，室温 20度上下  发热感觉明显，很不正常

**Comment by Skyxim** [comment]
暂时关闭确认具体原因

**Comment by id77** [comment]
有的api直接reject会死循环的，会不断发出后拦截，再发出。

使用解析器删除有问题规则，或替换成reject-dict，你可以试试看。

```conf
^https?:\/\/example\.com\/1 url reject
^https?:\/\/example\.com\/2 url reject-img
^https?:\/\/example\.com\/3 url reject-200
^https?:\/\/example\.com\/4 url reject-dict
^https?:\/\/example\.com\/5 url reject-array
```

这些类型都是有意义的。

**Comment by Skyxim** [comment]
> 有的api直接reject会死循环的，会不断发出后拦截，再发出。
> 
> 使用解析器删除有问题规则，或替换成reject-dict，你可以试试看。
> 
> ```
> ^https?:\/\/example\.com\/1 url reject
> ^https?:\/\/example\.com\/2 url reject-img
> ^https?:\/\/example\.com\/3 url reject-200
> ^https?:\/\/example\.com\/4 url reject-dict
> ^https?:\/\/example\.com\/5 url reject-array
> ```
> 
> 这些类型都是有意义的。

我甚至尝试了删掉所有广告重写，仍然发热，不对是发烫，同一个视频 在loon或者不开代理软件下明显发热会低很多
