### ISSUE TITLE
feature request: adding support for VLESS protocol 

### ISSUE THREAD

**Issue by vndi** [crossutility/Quantumult-X#88]
As above mentioned, when Shadowsocks are easily be recognized and Vmess protocol stay silent for a while, Vless has become more and more use in the battle field with GFW. So can Quantumult X add support for Vless protocol in next update?

**Comment by YeeWee** [comment]
good point

**Comment by kingwkb** [comment]
we need it

**Comment by Coltonchan** [comment]
up
