### ISSUE TITLE
Quantumult X用的v2ray内核版本太低？

### ISSUE THREAD

**Issue by Balnea** [crossutility/Quantumult-X#95]
<img width="952" alt="Capture" src="https://user-images.githubusercontent.com/11453121/147170381-1cca455a-e75b-49fb-8c3a-b0fe2b4af6a0.PNG">
我平时手机用Quantumult X连接，桌面端用的core直接连接。core用的是最新版本。
是否quantumult x用的v2ray内核版本太低了？

**Comment by Code2qing** [comment]
服务端不要开启AEAD

**Comment by Balnea** [comment]
虽然带一个套和两个套效果一样，但是介于vmess的特征(始终会进行数据校验)，貌似none的速度效果反而不太好。
很早的一个帖子：
https://steemit.com/cn/@v2ray/3cjiux

**Comment by Balnea** [comment]
或是是否只是设置的问题。在quantumult x里面是无法找到altid这个设置参数的。
<img width="619" alt="Capture" src="https://user-images.githubusercontent.com/11453121/147337293-7f1a8e64-7479-40d6-a5cc-50326bf3ba50.PNG">

**Comment by Code2qing** [comment]
> 

就是让你服务端AlterID不要设置为0啊，报错已经很明显的说明了

**Comment by Code2qing** [comment]
> 或是是否只是设置的问题。在quantumult x里面是无法找到altid这个设置参数的。 <img alt="Capture" width="619" src="https://user-images.githubusercontent.com/11453121/147337293-7f1a8e64-7479-40d6-a5cc-50326bf3ba50.PNG">
就是让你服务端AlterID不要设置为0啊，报错已经很明显的说明了

**Comment by Balnea** [comment]
谢谢回复。但这个却是我恰恰想避免的解决方案。
我是希望quantumult x增加altid这个配置项目。

**Comment by lifetyper** [comment]
所以到现在quantumult x还不支持vmess的aead认证？

**Comment by Code2qing** [comment]
> 所以到现在quantumult x还不支持vmess的aead认证？

是的呢，协议特性支持基本和quantumult差不多

**Comment by Balnea** [comment]
哎，希望quantumult x能够改进。
另外，上述服务器修改altid不等于0的办法视乎不能解决问题。
可以通过修改v2ray的环境变量来实现。具体可以参考这个帖子：
https://github.com/v2fly/v2ray-core/issues/1509

**Comment by Balnea** [comment]
v1.0.27-build626 已经修复这个问题了。
